2024-04-14 10:32:54,283 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-04-14 10:32:54,283 INFO: [33mPress CTRL+C to quit[0m
2024-04-14 10:32:54,369 INFO: 127.0.0.1 - - [14/Apr/2024 10:32:54] "GET / HTTP/1.1" 200 -
2024-04-14 10:32:54,559 INFO: 127.0.0.1 - - [14/Apr/2024 10:32:54] "[36mGET /static/js/bundle.js HTTP/1.1[0m" 304 -
2024-04-14 10:32:54,840 INFO: 127.0.0.1 - - [14/Apr/2024 10:32:54] "[36mGET /static/js/bundle.js.map HTTP/1.1[0m" 304 -
2024-04-14 10:33:01,132 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:01] "GET / HTTP/1.1" 200 -
2024-04-14 10:33:01,326 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:01] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:33:01,909 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:01] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:33:03,411 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:03] "GET / HTTP/1.1" 200 -
2024-04-14 10:33:03,598 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:03] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:33:13,191 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:13] "GET / HTTP/1.1" 200 -
2024-04-14 10:33:13,301 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:13] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:33:13,771 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:13] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:33:30,773 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-04-14 10:33:30,773 INFO: [33mPress CTRL+C to quit[0m
2024-04-14 10:33:31,075 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:31] "GET / HTTP/1.1" 200 -
2024-04-14 10:33:31,265 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:31] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:33:31,689 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:31] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:33:34,690 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:34] "GET / HTTP/1.1" 200 -
2024-04-14 10:33:34,894 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:34] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:33:39,254 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 10:33:39,355 DEBUG: https://api.seatgeek.com:443 "GET /2/events HTTP/1.1" 403 230
2024-04-14 10:33:39,357 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 10:33:39,507 DEBUG: https://api.seatgeek.com:443 "GET /2/events?geoip=true&datetime_utc.gte=2024-04-14&datetime_utc.lte=2024-04-20 HTTP/1.1" 200 None
2024-04-14 10:33:42,048 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 332, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 244, in generate_mixed_result
    service = create_service()
              ^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 291, in create_service
    flow = InstalledAppFlow.from_client_secrets_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'
2024-04-14 10:33:42,050 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:42] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 10:33:49,082 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:49] "GET / HTTP/1.1" 200 -
2024-04-14 10:33:49,266 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:49] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:33:49,606 INFO: 127.0.0.1 - - [14/Apr/2024 10:33:49] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:34:30,766 INFO: 127.0.0.1 - - [14/Apr/2024 10:34:30] "GET / HTTP/1.1" 200 -
2024-04-14 10:34:30,960 INFO: 127.0.0.1 - - [14/Apr/2024 10:34:30] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:34:31,380 INFO: 127.0.0.1 - - [14/Apr/2024 10:34:31] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:40:30,962 INFO: 127.0.0.1 - - [14/Apr/2024 10:40:30] "GET / HTTP/1.1" 200 -
2024-04-14 10:40:31,380 INFO: 127.0.0.1 - - [14/Apr/2024 10:40:31] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:40:32,033 INFO: 127.0.0.1 - - [14/Apr/2024 10:40:32] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:40:32,063 INFO: 127.0.0.1 - - [14/Apr/2024 10:40:32] "GET /static/img/android-chrome-512x512.png HTTP/1.1" 200 -
2024-04-14 10:40:57,563 INFO: 127.0.0.1 - - [14/Apr/2024 10:40:57] "GET / HTTP/1.1" 200 -
2024-04-14 10:42:45,303 INFO: 127.0.0.1 - - [14/Apr/2024 10:42:45] "GET / HTTP/1.1" 200 -
2024-04-14 10:42:45,697 INFO: 127.0.0.1 - - [14/Apr/2024 10:42:45] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:42:46,450 INFO: 127.0.0.1 - - [14/Apr/2024 10:42:46] "[36mGET /static/img/android-chrome-512x512.png HTTP/1.1[0m" 304 -
2024-04-14 10:42:46,481 INFO: 127.0.0.1 - - [14/Apr/2024 10:42:46] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:43:33,833 INFO: 127.0.0.1 - - [14/Apr/2024 10:43:33] "GET / HTTP/1.1" 200 -
2024-04-14 10:43:34,194 INFO: 127.0.0.1 - - [14/Apr/2024 10:43:34] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:43:34,556 INFO: 127.0.0.1 - - [14/Apr/2024 10:43:34] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:43:34,582 INFO: 127.0.0.1 - - [14/Apr/2024 10:43:34] "[33mGET /android-chrome-512x512.png HTTP/1.1[0m" 404 -
2024-04-14 10:43:34,755 INFO: 127.0.0.1 - - [14/Apr/2024 10:43:34] "[36mGET /static/img/android-chrome-512x512.png HTTP/1.1[0m" 304 -
2024-04-14 10:43:45,367 INFO: 127.0.0.1 - - [14/Apr/2024 10:43:45] "GET / HTTP/1.1" 200 -
2024-04-14 10:43:45,690 INFO: 127.0.0.1 - - [14/Apr/2024 10:43:45] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:43:46,187 INFO: 127.0.0.1 - - [14/Apr/2024 10:43:46] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:43:46,509 INFO: 127.0.0.1 - - [14/Apr/2024 10:43:46] "[36mGET /static/img/android-chrome-512x512.png HTTP/1.1[0m" 304 -
2024-04-14 10:43:47,057 INFO: 127.0.0.1 - - [14/Apr/2024 10:43:47] "[33mGET /android-chrome-512x512.png HTTP/1.1[0m" 404 -
2024-04-14 10:44:03,470 INFO: 127.0.0.1 - - [14/Apr/2024 10:44:03] "GET / HTTP/1.1" 200 -
2024-04-14 10:44:03,684 INFO: 127.0.0.1 - - [14/Apr/2024 10:44:03] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:44:04,595 INFO: 127.0.0.1 - - [14/Apr/2024 10:44:04] "[36mGET /static/img/android-chrome-512x512.png HTTP/1.1[0m" 304 -
2024-04-14 10:44:04,601 INFO: 127.0.0.1 - - [14/Apr/2024 10:44:04] "[33mGET /android-chrome-512x512.png HTTP/1.1[0m" 404 -
2024-04-14 10:44:04,601 INFO: 127.0.0.1 - - [14/Apr/2024 10:44:04] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:44:15,943 INFO: 127.0.0.1 - - [14/Apr/2024 10:44:15] "GET / HTTP/1.1" 200 -
2024-04-14 10:44:16,154 INFO: 127.0.0.1 - - [14/Apr/2024 10:44:16] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:44:16,934 INFO: 127.0.0.1 - - [14/Apr/2024 10:44:16] "[33mGET /android-chrome-512x512.png HTTP/1.1[0m" 404 -
2024-04-14 10:44:16,935 INFO: 127.0.0.1 - - [14/Apr/2024 10:44:16] "[36mGET /static/img/android-chrome-512x512.png HTTP/1.1[0m" 304 -
2024-04-14 10:44:16,963 INFO: 127.0.0.1 - - [14/Apr/2024 10:44:16] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:45:37,818 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-04-14 10:45:37,818 INFO: [33mPress CTRL+C to quit[0m
2024-04-14 10:45:46,263 INFO: 127.0.0.1 - - [14/Apr/2024 10:45:46] "GET / HTTP/1.1" 200 -
2024-04-14 10:45:46,287 INFO: 127.0.0.1 - - [14/Apr/2024 10:45:46] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:45:46,494 INFO: 127.0.0.1 - - [14/Apr/2024 10:45:46] "GET /static/img/android-chrome-512x512.png HTTP/1.1" 200 -
2024-04-14 10:45:46,507 INFO: 127.0.0.1 - - [14/Apr/2024 10:45:46] "[33mGET /android-chrome-512x512.png HTTP/1.1[0m" 404 -
2024-04-14 10:45:47,894 INFO: 127.0.0.1 - - [14/Apr/2024 10:45:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-04-14 10:45:50,358 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 10:45:50,649 DEBUG: https://api.seatgeek.com:443 "GET /2/events HTTP/1.1" 403 230
2024-04-14 10:45:50,653 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 10:45:50,842 DEBUG: https://api.seatgeek.com:443 "GET /2/events?geoip=true&datetime_utc.gte=2024-04-14&datetime_utc.lte=2024-04-20 HTTP/1.1" 200 None
2024-04-14 10:45:54,014 DEBUG: Generated new state jZBigcI6J6hMcJiEx285G6FQpj0ako.
2024-04-14 10:46:44,612 INFO: 127.0.0.1 - - [14/Apr/2024 10:46:44] "GET / HTTP/1.1" 200 -
2024-04-14 10:46:44,823 INFO: 127.0.0.1 - - [14/Apr/2024 10:46:44] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:46:45,032 INFO: 127.0.0.1 - - [14/Apr/2024 10:46:45] "[33mGET /android-chrome-512x512.png HTTP/1.1[0m" 404 -
2024-04-14 10:46:45,033 INFO: 127.0.0.1 - - [14/Apr/2024 10:46:45] "GET /static/img/android-chrome-512x512.png HTTP/1.1" 200 -
2024-04-14 10:46:59,562 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 10:46:59,681 DEBUG: https://api.seatgeek.com:443 "GET /2/events HTTP/1.1" 403 230
2024-04-14 10:46:59,684 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 10:46:59,861 DEBUG: https://api.seatgeek.com:443 "GET /2/events?geoip=true&datetime_utc.gte=2024-04-14&datetime_utc.lte=2024-04-20 HTTP/1.1" 200 None
2024-04-14 10:47:02,877 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 10:47:03,021 DEBUG: https://api.seatgeek.com:443 "GET /2/events HTTP/1.1" 403 230
2024-04-14 10:47:03,024 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 10:47:03,380 DEBUG: Generated new state CBh5ZjbF4u31z1bzR1h7CZ7lvc4Yfv.
2024-04-14 10:47:03,403 DEBUG: https://api.seatgeek.com:443 "GET /2/events?geoip=true&datetime_utc.gte=2024-04-14&datetime_utc.lte=2024-04-20 HTTP/1.1" 200 None
2024-04-14 10:47:03,528 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 333, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 219, in generate_mixed_result
    free_activity_response = free_activity_model.generate_content(free_things_prompt)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 10:47:03,535 INFO: 127.0.0.1 - - [14/Apr/2024 10:47:03] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 10:47:03,591 INFO: 127.0.0.1 - - [14/Apr/2024 10:47:03] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:47:48,846 INFO: 127.0.0.1 - - [14/Apr/2024 10:47:48] "GET / HTTP/1.1" 200 -
2024-04-14 10:47:49,358 INFO: 127.0.0.1 - - [14/Apr/2024 10:47:49] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:47:49,939 INFO: 127.0.0.1 - - [14/Apr/2024 10:47:49] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:47:49,966 INFO: 127.0.0.1 - - [14/Apr/2024 10:47:49] "[33mGET /android-chrome-512x512.png HTTP/1.1[0m" 404 -
2024-04-14 10:47:49,983 INFO: 127.0.0.1 - - [14/Apr/2024 10:47:49] "[36mGET /static/img/android-chrome-512x512.png HTTP/1.1[0m" 304 -
2024-04-14 10:49:27,603 INFO: 127.0.0.1 - - [14/Apr/2024 10:49:27] "GET / HTTP/1.1" 200 -
2024-04-14 10:49:27,850 INFO: 127.0.0.1 - - [14/Apr/2024 10:49:27] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:49:28,314 INFO: 127.0.0.1 - - [14/Apr/2024 10:49:28] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:49:28,605 INFO: 127.0.0.1 - - [14/Apr/2024 10:49:28] "[36mGET /static/img/android-chrome-512x512.png HTTP/1.1[0m" 304 -
2024-04-14 10:53:53,219 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-04-14 10:53:53,219 INFO: [33mPress CTRL+C to quit[0m
2024-04-14 10:53:53,469 INFO: 127.0.0.1 - - [14/Apr/2024 10:53:53] "GET / HTTP/1.1" 200 -
2024-04-14 10:53:53,475 INFO: 127.0.0.1 - - [14/Apr/2024 10:53:53] "GET / HTTP/1.1" 200 -
2024-04-14 10:53:53,707 INFO: 127.0.0.1 - - [14/Apr/2024 10:53:53] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:53:54,127 INFO: 127.0.0.1 - - [14/Apr/2024 10:53:54] "GET /static/img/android-chrome-512x512.png HTTP/1.1" 200 -
2024-04-14 10:53:54,133 INFO: 127.0.0.1 - - [14/Apr/2024 10:53:54] "[33mGET /android-chrome-512x512.png HTTP/1.1[0m" 404 -
2024-04-14 10:53:54,926 INFO: 127.0.0.1 - - [14/Apr/2024 10:53:54] "GET / HTTP/1.1" 200 -
2024-04-14 10:53:55,140 INFO: 127.0.0.1 - - [14/Apr/2024 10:53:55] "[36mGET /static/js/bundle.js HTTP/1.1[0m" 304 -
2024-04-14 10:53:55,221 INFO: 127.0.0.1 - - [14/Apr/2024 10:53:55] "[33mGET /android-chrome-512x512.png HTTP/1.1[0m" 404 -
2024-04-14 10:53:55,242 INFO: 127.0.0.1 - - [14/Apr/2024 10:53:55] "[36mGET /static/img/android-chrome-512x512.png HTTP/1.1[0m" 304 -
2024-04-14 10:53:59,321 INFO: 127.0.0.1 - - [14/Apr/2024 10:53:59] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:54:00,109 INFO: 127.0.0.1 - - [14/Apr/2024 10:54:00] "GET / HTTP/1.1" 200 -
2024-04-14 10:54:00,472 INFO: 127.0.0.1 - - [14/Apr/2024 10:54:00] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:54:01,145 INFO: 127.0.0.1 - - [14/Apr/2024 10:54:01] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:54:01,213 INFO: 127.0.0.1 - - [14/Apr/2024 10:54:01] "[33mGET /android-chrome-512x512.png HTTP/1.1[0m" 404 -
2024-04-14 10:54:01,213 INFO: 127.0.0.1 - - [14/Apr/2024 10:54:01] "[36mGET /static/img/android-chrome-512x512.png HTTP/1.1[0m" 304 -
2024-04-14 10:54:04,239 INFO: 127.0.0.1 - - [14/Apr/2024 10:54:04] "GET / HTTP/1.1" 200 -
2024-04-14 10:54:04,435 INFO: 127.0.0.1 - - [14/Apr/2024 10:54:04] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:54:04,544 INFO: 127.0.0.1 - - [14/Apr/2024 10:54:04] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:54:04,596 INFO: 127.0.0.1 - - [14/Apr/2024 10:54:04] "[33mGET /android-chrome-512x512.png HTTP/1.1[0m" 404 -
2024-04-14 10:54:04,601 INFO: 127.0.0.1 - - [14/Apr/2024 10:54:04] "[36mGET /static/img/android-chrome-512x512.png HTTP/1.1[0m" 304 -
2024-04-14 10:55:58,009 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-04-14 10:55:58,009 INFO: [33mPress CTRL+C to quit[0m
2024-04-14 10:56:00,397 INFO: 127.0.0.1 - - [14/Apr/2024 10:56:00] "GET / HTTP/1.1" 200 -
2024-04-14 10:56:00,772 INFO: 127.0.0.1 - - [14/Apr/2024 10:56:00] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:56:00,889 INFO: 127.0.0.1 - - [14/Apr/2024 10:56:00] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:56:04,704 INFO: 127.0.0.1 - - [14/Apr/2024 10:56:04] "GET / HTTP/1.1" 200 -
2024-04-14 10:56:04,921 INFO: 127.0.0.1 - - [14/Apr/2024 10:56:04] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 10:56:05,075 INFO: 127.0.0.1 - - [14/Apr/2024 10:56:05] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 10:56:06,796 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 10:56:06,907 DEBUG: https://api.seatgeek.com:443 "GET /2/events HTTP/1.1" 403 230
2024-04-14 10:56:06,911 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 10:56:07,067 DEBUG: https://api.seatgeek.com:443 "GET /2/events?geoip=true&datetime_utc.gte=2024-04-14&datetime_utc.lte=2024-04-20 HTTP/1.1" 200 None
2024-04-14 10:56:10,910 DEBUG: Generated new state sIKL7rJVnHfZiIcdjmWHs2u04UFxJh.
2024-04-14 11:00:23,189 INFO: 127.0.0.1 - - [14/Apr/2024 11:00:23] "GET / HTTP/1.1" 200 -
2024-04-14 11:00:23,371 INFO: 127.0.0.1 - - [14/Apr/2024 11:00:23] "[36mGET /static/js/bundle.js HTTP/1.1[0m" 304 -
2024-04-14 11:00:23,502 INFO: 127.0.0.1 - - [14/Apr/2024 11:00:23] "[36mGET /static/js/bundle.js.map HTTP/1.1[0m" 304 -
2024-04-14 11:03:06,714 INFO: 127.0.0.1 - - [14/Apr/2024 11:03:06] "GET / HTTP/1.1" 200 -
2024-04-14 11:03:07,728 INFO: 127.0.0.1 - - [14/Apr/2024 11:03:07] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:03:08,354 INFO: 127.0.0.1 - - [14/Apr/2024 11:03:08] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 11:03:09,117 INFO: 127.0.0.1 - - [14/Apr/2024 11:03:09] "GET / HTTP/1.1" 200 -
2024-04-14 11:03:09,590 INFO: 127.0.0.1 - - [14/Apr/2024 11:03:09] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:03:35,991 INFO: 127.0.0.1 - - [14/Apr/2024 11:03:35] "GET / HTTP/1.1" 200 -
2024-04-14 11:03:36,438 INFO: 127.0.0.1 - - [14/Apr/2024 11:03:36] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:03:37,030 INFO: 127.0.0.1 - - [14/Apr/2024 11:03:37] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 11:04:14,978 INFO: 127.0.0.1 - - [14/Apr/2024 11:04:14] "GET / HTTP/1.1" 200 -
2024-04-14 11:04:15,146 INFO: 127.0.0.1 - - [14/Apr/2024 11:04:15] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:04:15,554 INFO: 127.0.0.1 - - [14/Apr/2024 11:04:15] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 11:04:18,305 INFO: 127.0.0.1 - - [14/Apr/2024 11:04:18] "GET / HTTP/1.1" 200 -
2024-04-14 11:04:18,557 INFO: 127.0.0.1 - - [14/Apr/2024 11:04:18] "[36mGET /static/js/bundle.js HTTP/1.1[0m" 304 -
2024-04-14 11:04:18,700 INFO: 127.0.0.1 - - [14/Apr/2024 11:04:18] "[36mGET /static/js/bundle.js.map HTTP/1.1[0m" 304 -
2024-04-14 11:04:40,216 INFO: 127.0.0.1 - - [14/Apr/2024 11:04:40] "GET / HTTP/1.1" 200 -
2024-04-14 11:04:40,388 INFO: 127.0.0.1 - - [14/Apr/2024 11:04:40] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:04:40,512 INFO: 127.0.0.1 - - [14/Apr/2024 11:04:40] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 11:05:05,167 INFO: 127.0.0.1 - - [14/Apr/2024 11:05:05] "GET / HTTP/1.1" 200 -
2024-04-14 11:05:05,540 INFO: 127.0.0.1 - - [14/Apr/2024 11:05:05] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:05:14,086 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-04-14 11:05:14,086 INFO: [33mPress CTRL+C to quit[0m
2024-04-14 11:05:17,016 INFO: 127.0.0.1 - - [14/Apr/2024 11:05:17] "GET / HTTP/1.1" 200 -
2024-04-14 11:05:17,462 INFO: 127.0.0.1 - - [14/Apr/2024 11:05:17] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:05:22,638 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:05:22,734 DEBUG: https://api.seatgeek.com:443 "GET /2/events HTTP/1.1" 403 230
2024-04-14 11:05:22,737 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:05:22,890 DEBUG: https://api.seatgeek.com:443 "GET /2/events?geoip=true&datetime_utc.gte=2024-04-14&datetime_utc.lte=2024-04-20 HTTP/1.1" 200 None
2024-04-14 11:05:26,600 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 245, in generate_mixed_result
    service = create_service()
              ^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 296, in create_service
    creds = flow.run_local_server(port=8000)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google_auth_oauthlib/flow.py", line 432, in run_local_server
    local_server = wsgiref.simple_server.make_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
2024-04-14 11:05:26,610 INFO: 127.0.0.1 - - [14/Apr/2024 11:05:26] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:05:47,965 INFO: 127.0.0.1 - - [14/Apr/2024 11:05:47] "GET / HTTP/1.1" 200 -
2024-04-14 11:05:48,268 INFO: 127.0.0.1 - - [14/Apr/2024 11:05:48] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:05:48,603 INFO: 127.0.0.1 - - [14/Apr/2024 11:05:48] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 11:05:54,354 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-04-14 11:05:54,354 INFO: [33mPress CTRL+C to quit[0m
2024-04-14 11:05:56,061 INFO: 127.0.0.1 - - [14/Apr/2024 11:05:56] "GET / HTTP/1.1" 200 -
2024-04-14 11:05:56,312 INFO: 127.0.0.1 - - [14/Apr/2024 11:05:56] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:05:58,869 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:05:58,973 DEBUG: https://api.seatgeek.com:443 "GET /2/events HTTP/1.1" 403 230
2024-04-14 11:05:58,977 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:05:59,126 DEBUG: https://api.seatgeek.com:443 "GET /2/events?geoip=true&datetime_utc.gte=2024-04-14&datetime_utc.lte=2024-04-20 HTTP/1.1" 200 None
2024-04-14 11:05:59,251 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 219, in generate_mixed_result
    free_activity_response = free_activity_model.generate_content(free_things_prompt)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:05:59,256 INFO: 127.0.0.1 - - [14/Apr/2024 11:05:59] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:06:18,659 INFO: 127.0.0.1 - - [14/Apr/2024 11:06:18] "GET / HTTP/1.1" 200 -
2024-04-14 11:06:19,047 INFO: 127.0.0.1 - - [14/Apr/2024 11:06:19] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:06:22,212 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-04-14 11:06:22,212 INFO: [33mPress CTRL+C to quit[0m
2024-04-14 11:06:23,391 INFO: 127.0.0.1 - - [14/Apr/2024 11:06:23] "GET / HTTP/1.1" 200 -
2024-04-14 11:06:23,626 INFO: 127.0.0.1 - - [14/Apr/2024 11:06:23] "[36mGET /static/js/bundle.js HTTP/1.1[0m" 304 -
2024-04-14 11:06:26,129 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:06:26,224 DEBUG: https://api.seatgeek.com:443 "GET /2/events HTTP/1.1" 403 230
2024-04-14 11:06:26,229 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:06:26,375 DEBUG: https://api.seatgeek.com:443 "GET /2/events?geoip=true&datetime_utc.gte=2024-04-14&datetime_utc.lte=2024-04-20 HTTP/1.1" 200 None
2024-04-14 11:06:29,587 DEBUG: Generated new state dMB8FPtk8YnRxMEIvVFwml2kY8Gadf.
2024-04-14 11:06:31,417 INFO: 127.0.0.1 - - [14/Apr/2024 11:06:31] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 11:07:31,042 INFO: 127.0.0.1 - - [14/Apr/2024 11:07:31] "GET / HTTP/1.1" 200 -
2024-04-14 11:07:31,503 INFO: 127.0.0.1 - - [14/Apr/2024 11:07:31] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:07:32,085 INFO: 127.0.0.1 - - [14/Apr/2024 11:07:32] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 11:08:18,844 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:18] "GET / HTTP/1.1" 200 -
2024-04-14 11:08:19,434 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:19] "[36mGET /static/js/bundle.js HTTP/1.1[0m" 304 -
2024-04-14 11:08:19,600 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:19] "[36mGET /static/js/bundle.js.map HTTP/1.1[0m" 304 -
2024-04-14 11:08:27,336 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:08:27,457 DEBUG: https://api.seatgeek.com:443 "GET /2/events HTTP/1.1" 403 230
2024-04-14 11:08:27,460 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:08:27,645 DEBUG: https://api.seatgeek.com:443 "GET /2/events?geoip=true&datetime_utc.gte=2024-04-14&datetime_utc.lte=2024-04-20 HTTP/1.1" 200 None
2024-04-14 11:08:30,610 DEBUG: Generated new state fgyDuwPeUtSEbyT4q5cdCCwRrKRWiE.
2024-04-14 11:08:39,746 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-04-14 11:08:39,747 INFO: [33mPress CTRL+C to quit[0m
2024-04-14 11:08:41,297 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:08:41,455 DEBUG: https://api.seatgeek.com:443 "GET /2/events HTTP/1.1" 403 230
2024-04-14 11:08:41,463 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:08:41,628 DEBUG: https://api.seatgeek.com:443 "GET /2/events?geoip=true&datetime_utc.gte=2024-04-14&datetime_utc.lte=2024-04-20 HTTP/1.1" 200 None
2024-04-14 11:08:41,787 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 219, in generate_mixed_result
    free_activity_response = free_activity_model.generate_content(free_things_prompt)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:41,800 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:41] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:42,037 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "OPTIONS /api?user_query=[object+Object]&geoip=undefined HTTP/1.1" 200 -
2024-04-14 11:08:42,038 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "OPTIONS /api?user_query=[object+Object]&geoip=undefined HTTP/1.1" 200 -
2024-04-14 11:08:42,099 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "OPTIONS /api?user_query=[object+Object]&geoip=undefined HTTP/1.1" 200 -
2024-04-14 11:08:42,108 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "OPTIONS /api?user_query=[object+Object]&geoip=undefined HTTP/1.1" 200 -
2024-04-14 11:08:42,108 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "OPTIONS /api?user_query=[object+Object]&geoip=undefined HTTP/1.1" 200 -
2024-04-14 11:08:42,109 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "OPTIONS /api?user_query=[object+Object]&geoip=undefined HTTP/1.1" 200 -
2024-04-14 11:08:42,204 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "OPTIONS /api?user_query=[object+Object]&geoip=undefined HTTP/1.1" 200 -
2024-04-14 11:08:42,206 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "OPTIONS /api?user_query=[object+Object]&geoip=undefined HTTP/1.1" 200 -
2024-04-14 11:08:42,209 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "OPTIONS /api?user_query=[object+Object]&geoip=undefined HTTP/1.1" 200 -
2024-04-14 11:08:42,307 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:42,308 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "OPTIONS /api?user_query=[object+Object]&geoip=undefined HTTP/1.1" 200 -
2024-04-14 11:08:42,309 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:42,678 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:42,681 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:42] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:43,112 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:43,114 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:43] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:43,492 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:43,494 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:43] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:43,803 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:43,805 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:43] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:44,152 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:44,154 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:44] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:44,441 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:44] "OPTIONS /api?user_query=[object+Object]&geoip=undefined HTTP/1.1" 200 -
2024-04-14 11:08:44,534 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:44,538 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:44] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:44,720 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:44,722 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:44] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:44,726 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:44] "GET / HTTP/1.1" 200 -
2024-04-14 11:08:44,953 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:44] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:08:45,029 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:45,031 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:45] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:45,300 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:45,302 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:45] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:45,627 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:45,631 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:45] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:46,053 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:08:46,057 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:46] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:08:56,722 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:56] "GET / HTTP/1.1" 200 -
2024-04-14 11:08:56,915 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:56] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:08:57,028 INFO: 127.0.0.1 - - [14/Apr/2024 11:08:57] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 11:09:10,213 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-04-14 11:09:10,213 INFO: [33mPress CTRL+C to quit[0m
2024-04-14 11:09:13,393 INFO: 127.0.0.1 - - [14/Apr/2024 11:09:13] "GET / HTTP/1.1" 200 -
2024-04-14 11:09:13,617 INFO: 127.0.0.1 - - [14/Apr/2024 11:09:13] "[36mGET /static/js/bundle.js HTTP/1.1[0m" 304 -
2024-04-14 11:09:14,951 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    suggestions = generate_mixed_result(user_query, geoip) # JSON of results
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 211, in generate_mixed_result
    event_response = get_seatgeek_results(query, geoip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 185, in get_seatgeek_results
    response = query_processing_model.generate_content(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 791, in generate_content
    response = rpc(
               ^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
2024-04-14 11:09:14,961 INFO: 127.0.0.1 - - [14/Apr/2024 11:09:14] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
2024-04-14 11:09:35,593 INFO: 127.0.0.1 - - [14/Apr/2024 11:09:35] "GET / HTTP/1.1" 200 -
2024-04-14 11:09:35,905 INFO: 127.0.0.1 - - [14/Apr/2024 11:09:35] "GET /static/js/bundle.js HTTP/1.1" 200 -
2024-04-14 11:09:36,627 INFO: 127.0.0.1 - - [14/Apr/2024 11:09:36] "GET /static/js/bundle.js.map HTTP/1.1" 200 -
2024-04-14 11:10:03,368 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:10:03,488 DEBUG: https://api.seatgeek.com:443 "GET /2/events HTTP/1.1" 403 230
2024-04-14 11:10:03,491 DEBUG: Starting new HTTPS connection (1): api.seatgeek.com:443
2024-04-14 11:10:03,678 DEBUG: https://api.seatgeek.com:443 "GET /2/events?geoip=true&datetime_utc.gte=2024-04-14&datetime_utc.lte=2024-04-20 HTTP/1.1" 200 None
2024-04-14 11:10:07,415 ERROR: Exception on /api [GET]
Traceback (most recent call last):
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 337, in api
    print(suggestions)
                  ^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 245, in generate_mixed_result
    service = create_service()
              ^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/hive/app.py", line 296, in create_service
    # Save the credentials for next ime
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashrithb/Documents/Projects/hive/env/lib/python3.12/site-packages/google_auth_oauthlib/flow.py", line 432, in run_local_server
    local_server = wsgiref.simple_server.make_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
2024-04-14 11:10:07,421 INFO: 127.0.0.1 - - [14/Apr/2024 11:10:07] "[35m[1mGET /api?user_query=[object+Object]&geoip=undefined HTTP/1.1[0m" 500 -
